CREATE VIEW VW_MI_PENDENCY (NO, POLICY_NO, POLICY_HOLDER_NAME, AGENT_NAME, AGENT_CODE, BRANCHREGION, SOURCE, REQUEST_TYPE, REQUEST_RECEIVING_DATE, PROCESS_STATUS, STANDARD_TAT, ACTUAL_PROCESS_TIME, OVER_TAT_DAY, NOTE, EXC_PARAM_REGION, EXC_PARAM_PERIOD) AS 
	SELECT 	'N/A' AS NO,
	p."NUMBER" AS POLICY_NO,
	u.LIFEGIVENNAME AS POLICY_HOLDER_NAME,
	c.AGENTNAME AS AGENT_NAME,
	c.COMMISSIONAGENTNO AS AGENT_CODE,
	c.CONTRACTBRANCH AS BRANCHREGION,
	w.SOURCE AS SOURCE,
	w.TRANSACTION_TYPE AS REQUEST_TYPE,
	c.PROPOSALRECEIVEDDATE AS REQUEST_RECEIVING_DATE,
	w.STATUS AS PROCESS_STATUS,
	'N/A' AS STANDARD_TAT,
	'N/A' AS ACTUAL_PROCESS_TIME,
	'N/A' AS OVER_TAT_DAY,
	d.DESCRIPTION AS NOTE,
	p.REGION_CODE AS EXC_PARAM_REGION,
	w.DATE_CREATED AS EXC_PARAM_PERIOD
	FROM 	CMDEV.PLANS p
	LEFT JOIN CMDEV.WORKITEMS w ON p."NUMBER" = w.PLAN_ID
	LEFT JOIN CMDEV.NOTES d ON w.ID = d.WORKITEM_ID
	LEFT JOIN ODSDEV.CONTRACT@ABC_LINK c ON p."NUMBER" = c.POLICYNO
	LEFT JOIN ODSDEV.CONTRACTSTATUS@ABC_LINK cs ON c.POLICYNO = cs.POLICYNO
	LEFT JOIN ODSDEV.UWWORKSHEET@ABC_LINK u ON cs.APPLICATIONNO = u.RECEIPT
	WHERE w.STATUS != 'Completed';