CREATE VIEW VW_MI_CONTRACT_CENTRE (NAM, THANG, CONTRACT_NO, POLICY_HOLDER, CALLERS_NAME, CALLERS_INFO, INFO_RELATED, CONTENT, ACTION, STATUS, CALLING_DATE, PIC, NOTES, RESOURCE, ID, CALLTYPE, SUB_INFO_RELATED, FOLLOWUP, FOLLOWUP_DEPT, FOLLOWUP_DATE, STT, REFERENCE_NUMBER, DATE_OF_RECEIPT, CUSTOMERS_CODE, CUSTOMER_NAME, TYPE_OF_REQUEST, RECEIVING_CHANNEL, PRIORITY_LEVEL, DETAIL, DEADLINE_LEADTIME, SLA_DATE, OWNER_DEPARTMENT, CREATED_BY, RESULT, COMPLETION_DATE, CONTRACT_TYPE, EXC_PARAM_REGION, EXC_PARAM_PERIOD) AS 
	SELECT 	'N/A' AS NAM,
	'N/A' AS THANG,
	p."NUMBER" AS CONTRACT_NO,
	u.LIFEGIVENNAME AS POLICY_HOLDER,
	'' AS CALLERS_NAME,
	'' AS CALLERS_INFO,
	'' AS INFO_RELATED,
	'' AS CONTENT,
	'' AS ACTION,
	w.STATUS AS STATUS,
	'N/A' AS CALLING_DATE,
	'N/A' AS PIC,
	d.DESCRIPTION AS NOTES,
	'' AS RESOURCE,
	'N/A' AS ID,
	'' AS CALLTYPE,
	'' AS SUB_INFO_RELATED,
	'N/A' AS FOLLOWUP,
	'' AS FOLLOWUP_DEPT,
	'N/A' AS FOLLOWUP_DATE,
	'N/A' AS STT,
	'N/A' AS REFERENCE_NUMBER,
	'' AS DATE_OF_RECEIPT,
	'' AS CUSTOMERS_CODE,
	'' AS CUSTOMER_NAME,
	'' AS TYPE_OF_REQUEST,
	'' AS RECEIVING_CHANNEL,
	'' AS PRIORITY_LEVEL,
	'' AS DETAIL,
	'N/A' AS DEADLINE_LEADTIME,
	w.SLA_DUE_DATE AS SLA_DATE,
	'' AS OWNER_DEPARTMENT,
	w.CREATED_BY AS CREATED_BY,
	'' AS RESULT,
	'N/A' AS COMPLETION_DATE,
	'' AS CONTRACT_TYPE,
	p.REGION_CODE AS EXC_PARAM_REGION,
	w.DATE_CREATED AS EXC_PARAM_PERIOD
	FROM CMDEV.PLANS p
	LEFT JOIN CMDEV.WORKITEMS w ON p."NUMBER" = w.PLAN_ID
	LEFT JOIN CMDEV.NOTES d ON w.ID = d.WORKITEM_ID
	LEFT JOIN ODSDEV.CONTRACT@ABC_LINK c ON p."NUMBER" = c.POLICYNO
	LEFT JOIN ODSDEV.CONTRACTSTATUS@ABC_LINK c1 ON c.POLICYNO = c1.POLICYNO
	LEFT JOIN ODSDEV.UWWORKSHEET@ABC_LINK u ON c1.APPLICATIONNO = u.RECEIPT
	WHERE w.PROCESS_CODE = 'CC_CS';