CREATE VIEW VW_MI_DATA_ENTRY (NO, PROPOSAL_NUMBER, POLICY_NUMBER, POLICY_OWNER, RECEIVE_TIME, ACTION_TIME, PENDING_TIME_HOUR, PENDING_REASON, DATA_ENTRY__USER, PRODUCT_NAME, STATUS, SUM_ASSURED, TOTAL_PREMIUM, AGENT_NUMBER, AGENT_NAME, DISTRIBUTION_CHANNEL, EXC_PARAM_REGION, EXC_PARAM_PERIOD) AS 
	SELECT 	'N/A' AS NO,
	c.APPLICATIONNO AS PROPOSAL_NUMBER,
	p."NUMBER" AS POLICY_NUMBER,
	c1.PROPOSALNAME AS POLICY_OWNER,
	c1.PROPOSALRECEIVEDDATE AS RECEIVE_TIME,
	v.DATE_MODIFIED AS ACTION_TIME,
	'CALCULATED_FIELD' AS PENDING_TIME_HOUR,
	'' AS PENDING_REASON,
	v.MODIFIED_BY AS DATA_ENTRY__USER,
	'N/A' AS PRODUCT_NAME,
	v.STATUS AS STATUS,
	u.SUMASSURED AS SUM_ASSURED,
	'N/A' AS TOTAL_PREMIUM,
	c1.COMMISSIONAGENTNO AS AGENT_NUMBER,
	c1.AGENTNAME AS AGENT_NAME,
	'N/A' AS DISTRIBUTION_CHANNEL,
	p.REGION_CODE AS EXC_PARAM_REGION,
	v.DATE_CREATED AS EXC_PARAM_PERIOD
	FROM CMDEV.PLANS p
	LEFT JOIN CMDEV.WORKITEMS w ON p."NUMBER" = w.PLAN_ID
	LEFT JOIN CMDEV.QUEUES v ON w.ID = v.WORKITEM_ID
	LEFT JOIN ODSDEV.CONTRACT@ABC_LINK c ON p."NUMBER" = c.POLICYNO
	LEFT JOIN ODSDEV.CONTRACTSTATUS@ABC_LINK c1 ON c.POLICYNO = c1.POLICYNO
	LEFT JOIN ODSDEV.UWWORKSHEET@ABC_LINK u ON c1.APPLICATIONNO = u.RECEIPT
	WHERE v.TASK_CODE = 'NB_DE_DE'
	AND w.STATUS != 'Completed';